services:
  app: &app
    image: davifeliciano/nobel:latest
    container_name: nobel
    expose:
      - "8000"
    environment: &appenv
      DATABASE_URL: "postgres://postgres:postgres@db:5432/nobel"
      VALKEY_HOST: "valkey"
      VALKEY_PORT: 6379
      VALKEY_DB: 0
    depends_on:
      - db
      - valkey

  app_replica:
    <<: *app
    container_name: nobel_replica
    environment:
      <<: *appenv

  nginx:
    image: nginx:1.27.4-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nobel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro

  valkey:
    image: valkey/valkey:7.2.8-alpine
    container_name: valkey
    ports:
      - "6379:6379"
    command: ["valkey-server", "--save", "60", "1", "--loglevel", "warning"]

volumes:
  postgres_data:
