{
 "title": "Nobel Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate /laureates/physics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(request_count_total{endpoint=~\"/laureates/physics\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Rate /laureates/physics/:id",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(request_count_total{endpoint=\"/laureates/physics\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Response Latency (/laureates/physics)",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "response_latency_bucket{endpoint=\"/laureates/physics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Latency (/laureates/physics/1)",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "response_latency_bucket{endpoint=\"/laureates/physics/1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum by(status) (rate(error_count_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}