apiVersion: apps/v1
kind: Deployment
metadata:
  name: nobel-app
  labels:
    app: nobel-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nobel-app
  template:
    metadata:
      labels:
        app: nobel-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: nobel-app
        image: davifeliciano/nobel:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:postgres@nobel-db:5432/nobel"
        - name: VALKEY_HOST
          value: "nobel-valkey"
        - name: VALKEY_PORT
          value: "6379"
        - name: VALKEY_DB
          value: "0"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"