apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: nobel
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'nobel-app'
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - nobel
        relabel_configs:
          # Keep only pods with the label app=nobel-app
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: nobel-app
          # Use the pod's IP and port as the instance label
          - source_labels: [__address__]
            action: replace
            target_label: instance
          # Add the pod name as a label
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod
          # Remove unnecessary Kubernetes-generated labels
          - action: labeldrop
            regex: __meta_kubernetes_pod_label_.*
