name: Build and Deploy on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        TAG=${GITHUB_REF##*/}
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nobel:$TAG .

    - name: Tag image as latest
      run: |
        TAG=${GITHUB_REF##*/}
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/nobel:$TAG ${{ secrets.DOCKERHUB_USERNAME }}/nobel:latest

    - name: Push Docker image
      run: |
        TAG=${GITHUB_REF##*/}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/nobel:$TAG
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/nobel:latest

    - name: Rollout Kubernetes deployment
      run: |
        kubectl rollout restart deployment/nobel-app -n nobel
        kubectl rollout status deployment/nobel-app -n nobel